Repository OHDSI/WebAPI, pull requests merged in 2020-09, with the labels that each got.

#1616 added endpoint for cdm observation period report
  src/main/java/org/ohdsi/webapi/report/CDMObservationPeriod.java
  src/main/java/org/ohdsi/webapi/report/CDMResultsAnalysisRunner.java
  src/main/java/org/ohdsi/webapi/service/CDMResultsService.java
  src/main/resources/resources/cdmresults/sql/report/observationperiod/agebygender.sql
  src/main/resources/resources/cdmresults/sql/report/observationperiod/observationlengthbyage.sql
  src/main/resources/resources/cdmresults/sql/report/observationperiod/observationlengthbygender.sql
Labels: Aug25-Sept7

#1617 url is now persisted after login
  src/main/java/org/ohdsi/webapi/shiro/filters/SendTokenInUrlFilter.java
Labels: Aug25-Sept7

#1619 dropped legacy cohort features code
  src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/CohortGenerationInfo.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/CohortGenerationInfoToCohortGenerationInfoDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/dto/CohortGenerationInfoDTO.java
  src/main/java/org/ohdsi/webapi/cohortfeatures/GenerateCohortFeaturesTasklet.java
  src/main/java/org/ohdsi/webapi/security/model/SourcePermissionSchema.java
  src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java
  src/main/java/org/ohdsi/webapi/service/CohortGenerationService.java
  src/main/java/org/ohdsi/webapi/service/DDLService.java
  src/main/java/org/ohdsi/webapi/service/FeatureExtractionService.java
  src/main/resources/db/migration/oracle/V2.8.0.20200903120903__drop-cohort-features-columns.sql
  src/main/resources/db/migration/postgresql/V2.8.0.20200903120903__drop-cohort-features-columns.sql
  src/main/resources/db/migration/sqlserver/V2.8.0.20200903120903__drop-cohort-features-columns.sql
  src/main/resources/ddl/results/cohort_features.sql
  src/main/resources/ddl/results/cohort_features_analysis_ref.sql
  src/main/resources/ddl/results/cohort_features_dist.sql
  src/main/resources/ddl/results/cohort_features_ref.sql
  src/main/resources/resources/cohortdefinition/sql/cleanupResults.sql
  src/main/resources/resources/cohortfeatures/sql/queryCovariateDist.sql
  src/main/resources/resources/cohortfeatures/sql/queryCovariateDistVocab.sql
  src/main/resources/resources/cohortfeatures/sql/queryCovariateStats.sql
  src/main/resources/resources/cohortfeatures/sql/queryCovariateStatsVocab.sql
Labels: Aug25-Sept7

#1621 createPs is set to true when user specifies inverse probability of treatment weighting (IPTW) for the outcome model
  src/main/java/org/ohdsi/webapi/check/builder/IterableForEachValidatorBuilder.java
  src/main/java/org/ohdsi/webapi/check/builder/PredicateValidatorBuilder.java
  src/main/java/org/ohdsi/webapi/check/builder/ValidatorBaseBuilder.java
  src/main/java/org/ohdsi/webapi/check/checker/estimation/helper/EstimationAnalysisSpecificationHelper.java
  src/main/java/org/ohdsi/webapi/check/validator/Validator.java
  src/main/java/org/ohdsi/webapi/check/validator/common/NotNullNotEmptyValidator.java
  src/main/java/org/ohdsi/webapi/check/validator/common/PredicateValidator.java
Labels: Sept8-Sept21

#1628 Excludes cdm-only sources from caching
  src/main/java/org/ohdsi/webapi/service/CDMResultsService.java
  src/main/java/org/ohdsi/webapi/source/Source.java
  src/main/java/org/ohdsi/webapi/util/SourceUtils.java
Labels: Sept8-Sept21

#1626 excludes deleted sources from query results
  src/main/java/org/ohdsi/webapi/source/SourceDaimonRepository.java
Labels: Sept8-Sept21

#1629 Update V2.8.0.20200903120903__drop-cohort-features-columns.sql
  src/main/resources/db/migration/sqlserver/V2.8.0.20200903120903__drop-cohort-features-columns.sql
Labels: Sept8-Sept21

#1623 Each auth provider can be disabled. For details see README.md
  README.md
  pom.xml
  src/main/java/org/ohdsi/webapi/shiro/management/AtlasRegularSecurity.java
  src/main/resources/application.properties
Labels: Sept8-Sept21

#1587 Updated hydra version
  pom.xml
  src/main/resources/resources/estimation/r/runAnalysis.R
  src/main/resources/resources/prediction/r/runAnalysis.R
  src/main/resources/resources/prediction/skeleton/SkeletonPredictionStudy_0.0.1.zip
Labels: Aug11-Aug24, Aug25-Sept7, July28-Aug10, Sept8-Sept21

#1461 Implemented Concept Set editor for Feature Analysis and CC
  src/main/java/org/ohdsi/webapi/cohortcharacterization/CcController.java
  src/main/java/org/ohdsi/webapi/cohortcharacterization/CcService.java
  src/main/java/org/ohdsi/webapi/cohortcharacterization/CcServiceImpl.java
  src/main/java/org/ohdsi/webapi/conceptset/ExportUtil.java
  src/main/java/org/ohdsi/webapi/conceptset/converter/ConceptSetToExportConverter.java
  src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisController.java
  src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisService.java
  src/main/java/org/ohdsi/webapi/feanalysis/FeAnalysisServiceImpl.java
  src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java
  src/main/java/org/ohdsi/webapi/service/VocabularyService.java
  src/main/java/org/ohdsi/webapi/util/HttpUtils.java
  src/main/resources/db/migration/sqlserver/V20200213165742__export-conceptsets-permissions.sql
Labels: June2-June15

#1632 Prevent trailing white spaces in asset names #1510
  src/main/java/org/ohdsi/webapi/cohortcharacterization/converter/BaseCcDTOToCcEntityConverter.java
  src/main/java/org/ohdsi/webapi/cohortcharacterization/converter/BaseCcToCcShortDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/BaseCohortDTOToCohortDefinitionConverter.java
  src/main/java/org/ohdsi/webapi/estimation/EstimationServiceImpl.java
  src/main/java/org/ohdsi/webapi/estimation/converter/EstimationToEstimationShortDTOConverter.java
  src/main/java/org/ohdsi/webapi/feanalysis/converter/BaseFeAnalysisDTOToFeAnalysisConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/BasePathwayAnalysisDTOToPathwayAnalysisConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/BasePathwayAnalysisToPathwayAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/BasePathwayCohortDTOToPathwayCohortConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/BasePathwayCohortToPathwayCohortDTOConverter.java
  src/main/java/org/ohdsi/webapi/prediction/PredictionServiceImpl.java
  src/main/java/org/ohdsi/webapi/prediction/converter/PredictionAnalysisToCommonAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java
  src/main/java/org/ohdsi/webapi/service/IRAnalysisService.java
  src/main/java/org/ohdsi/webapi/service/converters/ConceptSetDTOToConceptSetConverter.java
  src/main/java/org/ohdsi/webapi/service/converters/IncidenceRateAnalysisToIRAnalysisShortDTOConverter.java
Labels: Sept22-Oct5, Sept8-Sept21

#1483 issue-1117 check permission against only jwt-auth-realm + upgrade shi…
  pom.xml
  src/main/java/org/ohdsi/webapi/ShiroConfiguration.java
  src/main/java/org/ohdsi/webapi/shiro/AtlasWebSecurityManager.java
  src/main/java/org/ohdsi/webapi/shiro/TokenManager.java
  src/main/java/org/ohdsi/webapi/shiro/filters/UpdateAccessTokenFilter.java
  src/main/java/org/ohdsi/webapi/shiro/filters/auth/AtlasJwtAuthFilter.java
  src/main/java/org/ohdsi/webapi/shiro/lockout/LockoutWebSecurityManager.java
  src/main/java/org/ohdsi/webapi/shiro/management/AtlasRegularSecurity.java
  src/main/java/org/ohdsi/webapi/shiro/management/AtlasSecurity.java
  src/main/java/org/ohdsi/webapi/shiro/management/DisabledSecurity.java
  src/main/java/org/ohdsi/webapi/shiro/management/Security.java
  src/main/java/org/ohdsi/webapi/shiro/realms/ADRealm.java
  src/main/java/org/ohdsi/webapi/shiro/realms/JdbcAuthRealm.java
  src/main/java/org/ohdsi/webapi/shiro/realms/JwtAuthRealm.java
  src/main/java/org/ohdsi/webapi/shiro/realms/KerberosAuthRealm.java
  src/main/java/org/ohdsi/webapi/shiro/realms/LdapRealm.java
  src/main/java/org/ohdsi/webapi/shiro/tokens/JwtAuthToken.java
Labels: Aug11-Aug24, Sept22-Oct5, Sept8-Sept21
