Repository OHDSI/WebAPI, pull requests merged in 2020-08, with the labels that each got.

#1568 Added possibility to get system and user notifications
  src/main/java/org/ohdsi/webapi/Constants.java
  src/main/java/org/ohdsi/webapi/job/JobExecutionInfo.java
  src/main/java/org/ohdsi/webapi/job/JobExecutionResource.java
  src/main/java/org/ohdsi/webapi/job/JobExecutionToDTOConverter.java
  src/main/java/org/ohdsi/webapi/job/JobOwnerType.java
  src/main/java/org/ohdsi/webapi/job/JobTemplate.java
  src/main/java/org/ohdsi/webapi/job/NotificationController.java
  src/main/java/org/ohdsi/webapi/job/NotificationService.java
  src/main/java/org/ohdsi/webapi/job/NotificationServiceImpl.java
  src/main/java/org/ohdsi/webapi/user/importer/service/UserImportJobServiceImpl.java
Labels: July28-Aug10

#1583 Merges Achilles report caching improvements from 2.7.8
  pom.xml
  src/main/java/org/ohdsi/webapi/CacheConfig.java
  src/main/java/org/ohdsi/webapi/Constants.java
  src/main/java/org/ohdsi/webapi/cache/CacheService.java
  src/main/java/org/ohdsi/webapi/cdmresults/BaseCDMResultsCacheTasklet.java
  src/main/java/org/ohdsi/webapi/cdmresults/CDMResultsCacheTasklet.java
  src/main/java/org/ohdsi/webapi/cdmresults/DashboardCacheTasklet.java
  src/main/java/org/ohdsi/webapi/cdmresults/DataDensityCacheTasklet.java
  src/main/java/org/ohdsi/webapi/cdmresults/PersonCacheTasklet.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/CDMEvictionAdvisor.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/CDMResultsSupport.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/DashboardEvictionAdvisor.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/DataDensityEvictionAdivisor.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/DrilldownEvictionAdvisor.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/PersonEvictionAdvisor.java
  src/main/java/org/ohdsi/webapi/cdmresults/eviction/TreemapEvictionAdvisor.java
  src/main/java/org/ohdsi/webapi/cdmresults/keys/DrilldownKey.java
  src/main/java/org/ohdsi/webapi/cdmresults/keys/DrilldownKeyGenerator.java
  src/main/java/org/ohdsi/webapi/cdmresults/keys/RefreshableSourceKey.java
  src/main/java/org/ohdsi/webapi/cdmresults/keys/RefreshableSourceKeyGenerator.java
  src/main/java/org/ohdsi/webapi/cdmresults/keys/TreemapKey.java
  src/main/java/org/ohdsi/webapi/cdmresults/keys/TreemapKeyGenerator.java
  src/main/java/org/ohdsi/webapi/report/CDMAttribute.java
  src/main/java/org/ohdsi/webapi/report/CDMDashboard.java
  src/main/java/org/ohdsi/webapi/report/CDMPersonSummary.java
  src/main/java/org/ohdsi/webapi/report/CDMResultsAnalysisRunner.java
  src/main/java/org/ohdsi/webapi/report/CohortStatsRecord.java
  src/main/java/org/ohdsi/webapi/report/ConceptCountRecord.java
  src/main/java/org/ohdsi/webapi/report/ConceptDistributionRecord.java
  src/main/java/org/ohdsi/webapi/report/CumulativeObservationRecord.java
  src/main/java/org/ohdsi/webapi/report/MonthObservationRecord.java
  src/main/java/org/ohdsi/webapi/service/CDMResultsService.java
  src/main/java/org/ohdsi/webapi/shiro/management/AtlasSecurity.java
  src/main/resources/application.properties
  src/main/resources/config/ehcache.xml
  src/test/java/org/ohdsi/webapi/test/CacheServiceIT.java
Labels: July28-Aug10

#1609 backmerge fixes issue with permissions
  src/main/resources/db/migration/oracle/V2.7.8.20200728164800__add_conceptset_permission.sql
  src/main/resources/db/migration/postgresql/V2.7.8.20200728164800__add_conceptset_permission.sql
  src/main/resources/db/migration/sqlserver/V2.7.8.20200728164800__add_conceptset_permission.sql
Labels: Aug11-Aug24

#1608 Updates CohortCharacterization Skeleton version from 2.7.8
  pom.xml
Labels: Aug11-Aug24

#1509 merge geo spatial into 2.8
  README.md
  pom.xml
  src/main/java/org/ohdsi/webapi/plugins/AtlasGisConfig.java
  src/main/java/org/ohdsi/webapi/plugins/PluginsConfigurationInfo.java
  src/main/resources/application.properties
  src/main/resources/db/migration/oracle/V2.8.0.20200413150815__gis_service_api.sql
  src/main/resources/db/migration/postgresql/V2.8.0.20200413150815__gis_service_api.sql
  src/main/resources/db/migration/sqlserver/V2.8.0.20200413150815__gis_service_api.sql
Labels: Aug11-Aug24, July28-Aug10

#1556 Add "Shared with me" flag to common entities
  src/main/java/org/ohdsi/webapi/cohortcharacterization/converter/BaseCcToCcShortDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortcharacterization/converter/SerializedCcToCcConverter.java
  src/main/java/org/ohdsi/webapi/cohortcharacterization/dto/CcShortDTO.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/BaseCohortDefinitionToCohortMetadataDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/CohortDefinitionToCohortDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/CohortDefinitionToCohortMetadataDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/CohortDefinitionToCohortRawDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/dto/CohortMetadataDTO.java
  src/main/java/org/ohdsi/webapi/common/analyses/CommonAnalysisDTO.java
  src/main/java/org/ohdsi/webapi/estimation/converter/EstimationToEstimationDTOConverter.java
  src/main/java/org/ohdsi/webapi/estimation/converter/EstimationToEstimationShortDTOConverter.java
  src/main/java/org/ohdsi/webapi/feanalysis/converter/BaseFeAnalysisEntityToFeAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/BasePathwayAnalysisToPathwayAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/PathwayAnalysisToPathwayAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/pathway/converter/PathwayAnalysisToPathwayAnalysisExportDTOConverter.java
  src/main/java/org/ohdsi/webapi/pathway/dto/BasePathwayAnalysisDTO.java
  src/main/java/org/ohdsi/webapi/prediction/converter/PredictionAnalysisToCommonAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/prediction/converter/PredictionAnalysisToPredictionAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/security/PermissionService.java
  src/main/java/org/ohdsi/webapi/security/model/UserSimpleAuthorizationInfo.java
  src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java
  src/main/java/org/ohdsi/webapi/service/converters/BaseCommonEntityToDTOConverter.java
  src/main/java/org/ohdsi/webapi/service/converters/ConceptSetToConceptSetDTOConverter.java
  src/main/java/org/ohdsi/webapi/service/converters/IncidenceRateAnalysisToIRAnalysisDTOConverter.java
  src/main/java/org/ohdsi/webapi/service/converters/IncidenceRateAnalysisToIRAnalysisShortDTOConverter.java
  src/main/java/org/ohdsi/webapi/service/dto/CommonEntityDTO.java
  src/main/java/org/ohdsi/webapi/shiro/Entities/PermissionRepository.java
  src/main/java/org/ohdsi/webapi/shiro/PermissionManager.java
  src/main/java/org/ohdsi/webapi/shiro/filters/CacheFilter.java
  src/main/java/org/ohdsi/webapi/user/dto/UserDTO.java
  src/main/java/org/ohdsi/webapi/util/ConversionUtils.java
Labels: Aug11-Aug24

#1613 do not show amount file for plp/ple download button (#1530)
  src/main/java/org/ohdsi/webapi/common/generation/ExecutionEngineGenerationEntityToDtoConverter.java
  src/main/java/org/ohdsi/webapi/executionengine/controller/ScriptExecutionCallbackController.java
  src/main/java/org/ohdsi/webapi/executionengine/entity/ExecutionEngineAnalysisStatus.java
  src/main/java/org/ohdsi/webapi/executionengine/service/AnalysisZipRepackService.java
  src/main/java/org/ohdsi/webapi/executionengine/service/AnalysisZipUtils.java
  src/main/resources/db/migration/oracle/V2.7.7.20200430193000__add_amount_files_in_analysis_result.sql
  src/main/resources/db/migration/postgresql/V2.7.7.20200430193000__add_amount_files_in_analysis_result.sql
  src/main/resources/db/migration/sqlserver/V2.7.7.20200430193000__add_amount_files_in_analysis_result.sql
  src/test/java/org/ohdsi/webapi/executionengine/service/AnalysisZipRepackServiceTest.java
Labels: Aug11-Aug24

#1527 cohort generation process and status is now visible to another users
  src/main/java/org/ohdsi/webapi/cohortdefinition/CohortGenerationInfo.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/converter/CohortGenerationInfoToCohortGenerationInfoDTOConverter.java
  src/main/java/org/ohdsi/webapi/cohortdefinition/dto/CohortGenerationInfoDTO.java
  src/main/java/org/ohdsi/webapi/service/CohortDefinitionService.java
  src/main/java/org/ohdsi/webapi/service/CohortGenerationService.java
  src/main/resources/db/migration/oracle/V2.8.0.20200428122109__add_created_by_to_cohort_generation_info.sql
  src/main/resources/db/migration/postgresql/V2.8.0.20200428122109__add_created_by_to_cohort_generation_info.sql
  src/main/resources/db/migration/sqlserver/V2.8.0.20200428122109__add_created_by_to_cohort_generation_info.sql
Labels: Aug11-Aug24, Aug25-Sept7
